import Button from '../components/Button'
import Card from '../components/Card'
import Container from '../components/Container'
import PageMeta from '../components/PageMeta'
import SectionHeading from '../components/SectionHeading'
import SectionCTA from '../components/SectionCTA'
import { config, whatsappUrl } from '../config'

const tracks = [['IA aplicada al trabajo', 'Capacidades, límites, automatización y uso responsable.'], ['LLMs, Agents & AI Engineering', 'Contexto, herramientas, workflows, agentes, RAG, MCP, evaluación y revisión humana.'], ['AI Coding & SDLC', 'Uso de IA en ingeniería, controles, medición, seguridad y adopción.'], ['Arquitectura, Data & AI', 'Cómo conectar modelos con APIs, datos, cloud y sistemas existentes.']]

export default function Academy() {
  return <><PageMeta path="/academy" title="Neuracode Academy | Formación en IA, Agentes y AI Engineering" description="Talleres y formación práctica para profesionales y equipos en IA, LLMs, agentes, AI Engineering, AI Coding, SDLC y adopción segura." />
    <section className="page-hero academy-hero"><Container><p className="eyebrow">Neuracode Academy</p><h1>Formación práctica en IA para profesionales y equipos.</h1><p>Aprende a utilizar, diseñar e integrar IA con fundamentos de software, datos, arquitectura, seguridad y operación real.</p><Button href={whatsappUrl('academy')} target="_blank" rel="noreferrer">Consultar formación</Button></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Rutas de aprendizaje" title="Aprender desde problemas que existen fuera del aula."/><div className="grid grid-4 motion-grid">{tracks.map(([title,description],i)=><Card key={title}><span className="card-index">0{i+1}</span><h3>{title}</h3><p>{description}</p></Card>)}</div><SectionCTA title="¿Qué necesita aprender tu equipo?" description="Conversemos sobre el punto de partida y el formato que encaja con su trabajo." intent="formacion" label="Agendar una conversación"/></Container></section>
    <section className="section section-tint"><Container><div className="split"><div><p className="eyebrow">Para equipos</p><h2>Formación conectada al trabajo real.</h2><p>Diseñamos talleres y programas corporativos a partir de los procesos, herramientas, capacidades y riesgos reales de cada organización.</p><div className="chip-row"><span>LLMs</span><span>Agentes</span><span>AI Coding</span><span>Agentic SDLC</span><span>MCP</span><span>RAG</span><span>AI Security</span></div></div><div><p className="eyebrow">Experiencia técnica + docente</p><h2>La experiencia de implementación mejora la formación.</h2><p>Jack Aguilar es Instructor de Agentes de Inteligencia Artificial en SDC Learning y desarrolla workshops mediante Neuracode Academy.</p><Card><h3>De aprender a implementar</h3><p>Cuando un equipo necesita pasar del aprendizaje a la ejecución, podemos continuar con discovery, un piloto acotado o acompañamiento técnico.</p></Card></div></div><SectionCTA title="Diseñemos una formación útil para el trabajo real." description="Definimos audiencia, objetivos, herramientas y límites antes de proponer un programa." intent="formacion" label="Agendar formación"/></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Aprendizaje abierto" title="Workshops, webinars y recursos prácticos." description="Contenido para profesionales que quieren aplicar IA, ingeniería de software y sistemas agénticos con fundamentos."/><div className="social-row">{config.socials.academy.map(s=><a key={s.label} href={s.url} target="_blank" rel="noreferrer">Academy en {s.label} ↗</a>)}</div><Button href={whatsappUrl('academy')} target="_blank" rel="noreferrer" variant="secondary">Quiero recibir próximos eventos</Button></Container></section>
    <section className="cta"><Container><p className="eyebrow">Siguiente paso</p><h2>¿Tu equipo necesita pasar del aprendizaje a la ejecución?</h2><p>Conversemos sobre el contexto, las capacidades y el formato de formación que mejor se adapta a su trabajo.</p><Button href={whatsappUrl('formacion')} target="_blank" rel="noreferrer">Conversar sobre formación</Button></Container></section>
  </>
}
