import Button from '../components/Button'
import Card from '../components/Card'
import Container from '../components/Container'
import PageMeta from '../components/PageMeta'
import SectionHeading from '../components/SectionHeading'
import { consultingExperience, currentWork, professionalExperience, selectedWork, type EvidenceItem } from '../content'
import { whatsappUrl } from '../config'
const Grid=({items}:{items:EvidenceItem[]})=><div className="grid grid-3">{items.map(item=><Card key={item.id}><p className="evidence-label">{item.label}</p><h3>{item.title}</h3>{item.organization&&<p className="organization">{item.organization}</p>}<p>{item.summary}</p><div className="chip-row">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div>{item.url&&<a className="text-link" href={item.url} target="_blank" rel="noreferrer">Ver evidencia pública ↗</a>}</Card>)}</div>
export default function Casos(){return <><PageMeta path="/casos" title="Casos y Experiencia en IA, Automatización y Software | Neuracode" description="Proyectos, experiencia profesional y trabajo técnico en automatización, agentes, datos, software empresarial y Secure / Agentic SDLC."/><section className="page-hero"><Container><p className="eyebrow">Casos y experiencia</p><h1>Casos, experiencia y evidencia.</h1><p>Separamos proyectos públicos, experiencia profesional, engagements de consultoría y trabajo actual para que cada afirmación tenga el contexto correcto.</p></Container></section><section className="section"><Container><SectionHeading eyebrow="Selected Case Studies" title="Trabajo técnico público."/><Grid items={selectedWork}/></Container></section><section className="section section-tint"><Container><SectionHeading eyebrow="Selected Professional Experience" title="Experiencia que sustenta la práctica."/><Grid items={[...professionalExperience,...consultingExperience]}/></Container></section><section className="section"><Container><SectionHeading eyebrow="Current Work / Labs" title="Trabajo en curso, sin promesas de resultado." description="Estos engagements se muestran anonimizados y no se presentan como casos de éxito."/><Grid items={currentWork}/></Container></section><section className="cta"><Container><h2>¿Quieres evaluar una necesidad similar?</h2><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Evaluar una oportunidad</Button></Container></section></>}
