import Button from '../components/Button'
import Card from '../components/Card'
import Container from '../components/Container'
import PageMeta from '../components/PageMeta'
import SectionHeading from '../components/SectionHeading'
import { buyerScenarios, focusGroupProject, offers, primaryEcosystems, principles, technicalEcosystems } from '../content'
import { whatsappUrl } from '../config'

export default function Empresas() {
  return <><PageMeta path="/empresas" title="Consultoría de IA y Automatización para Empresas | Neuracode" description="Discovery, pilotos e implementación de automatización, agentes y sistemas de IA. Claude, OpenAI/Codex, Google Vertex AI, AWS Bedrock, datos, APIs y Secure SDLC." />
    <section className="page-hero"><Container><p className="eyebrow">Neuracode Enterprise</p><h1>Automatización, agentes y sistemas de IA para empresas.</h1><p>Convertimos procesos, datos e integraciones en soluciones de IA que pueden probarse, medirse y operar dentro de tu realidad tecnológica.</p><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Evaluar una oportunidad</Button></Container></section>
    <section className="section section-tint"><Container><SectionHeading eyebrow="Puedes llegar con..." title="No necesitas llegar con la arquitectura resuelta." description="El trabajo empieza entendiendo el proceso, los sistemas, los datos, las restricciones y el resultado que debe cambiar."/><div className="grid grid-3 scenario-grid">{buyerScenarios.map(item=><Card key={item}><p>“{item}”</p></Card>)}</div></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Ofertas" title="Una ruta clara desde discovery hasta operación."/><div className="grid grid-3">{offers.map((o,i)=><Card key={o.name}><span className="card-index">0{i+1}</span><h3>{o.name}</h3><p>{o.outcome}</p></Card>)}</div></Container></section>
    <section className="section section-dark"><Container><SectionHeading eyebrow="Proceso" title="Discovery → Arquitectura → Piloto → Integración → Evaluación → Operación."/><div className="principles">{principles.map((p,i)=><div key={p}><span>{i+1}</span><p>{p}</p></div>)}</div><p className="section-note">Seguridad, permisos, trazabilidad y observabilidad acompañan el proceso de extremo a extremo.</p><p className="section-note">La complejidad crece solo cuando el problema lo exige: automatización tradicional, workflow con LLM, agente o sistema agéntico.</p></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Prueba de trabajo" title="Experiencia para conectar IA con la operación."/><div className="grid grid-3"><Card><p className="evidence-label">Proyecto cuantificado</p><h3>50 entrevistas → insights validados</h3><p>{focusGroupProject.summary}</p><div className="metric-row">{focusGroupProject.metrics?.map(metric=><strong key={metric}>{metric}</strong>)}</div></Card><Card><p className="evidence-label">Ingeniería regulada</p><h3>Backend Java, arquitectura y seguridad</h3><p>Experiencia en banca y software empresarial regulado: Spring Boot, integración, resiliencia, seguridad y continuidad operativa.</p></Card><Card><p className="evidence-label">Datos y lenguaje</p><h3>Predictive AI y NLP</h3><p>Forecasting de demanda, analítica predictiva y automatización de lenguaje pre-LLM junto a arquitecturas generativas actuales.</p></Card></div></Container></section>
    <section className="section section-tint"><Container><div className="technology-buyer"><p className="eyebrow">Plataformas y patrones de implementación</p><h2>¿Ya tienes una tecnología definida?</h2><p>Podemos partir del proceso o de una plataforma ya elegida. Evaluamos integración, datos, permisos, seguridad, costo, observabilidad y operación antes de escalar.</p><div className="chip-row chip-row-primary">{primaryEcosystems.map(item=><span key={item}>{item}</span>)}</div><div className="chip-row">{technicalEcosystems.map(item=><span key={item}>{item}</span>)}</div><div className="faq-item"><h3>¿Trabajan con Claude, OpenAI, Vertex AI o AWS Bedrock?</h3><p>Sí. La selección depende del caso de uso, arquitectura existente, datos, seguridad, costo y operación. Cuando la mejor solución no necesita un LLM, también lo decimos.</p></div></div></Container></section>
    <section className="cta"><Container><h2>¿Tienes un proceso, producto o equipo que necesita avanzar con IA?</h2><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Hablar sobre el proyecto</Button></Container></section>
  </>
}
