import Button from '../components/Button'
import Card from '../components/Card'
import Container from '../components/Container'
import PageMeta from '../components/PageMeta'
import SectionHeading from '../components/SectionHeading'
import SectionCTA from '../components/SectionCTA'
import { buyerScenarios, focusGroupProject, offers, principles } from '../content'
import { whatsappUrl } from '../config'

export default function Empresas() {
  return <><PageMeta path="/empresas" title="Consultoría de IA y Automatización para Empresas | Neuracode" description="Discovery, pilotos e implementación de automatización, agentes y sistemas de IA. Claude, OpenAI/Codex, Google Vertex AI, AWS Bedrock, datos, APIs y Secure SDLC." />
    <section className="page-hero enterprise-hero"><Container><p className="eyebrow">Neuracode Enterprise</p><h1>Automatización, agentes y sistemas de IA para empresas.</h1><p>Convertimos procesos, datos e integraciones en soluciones de IA que pueden probarse, medirse y operar dentro de tu realidad tecnológica.</p><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Agendar una conversación</Button></Container></section>
    <section className="section section-tint"><Container><SectionHeading eyebrow="Puedes llegar con..." title="No necesitas llegar con la arquitectura resuelta." description="Partimos del problema que debe cambiar y ordenamos proceso, sistemas, datos y restricciones antes de proponer una solución."/><div className="grid grid-3 scenario-grid motion-grid">{buyerScenarios.map(item=><Card key={item}><p>“{item}”</p></Card>)}</div><SectionCTA title="¿Este es tu punto de partida?" description="Cuéntanos el proceso o sistema que quieres mejorar; la primera conversación sirve para ordenar el contexto."/></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Ofertas" title="Una ruta clara, sin empezar por la herramienta."/><div className="grid grid-3 motion-grid">{offers.map((o,i)=><Card key={o.name}><span className="card-index">0{i+1}</span><h3>{o.name}</h3><p>{o.outcome}</p></Card>)}</div><SectionCTA title="Define el siguiente paso correcto." description="Podemos empezar con discovery, un piloto acotado o una implementación, según el contexto."/></Container></section>
    <section className="section section-dark"><Container><SectionHeading eyebrow="Proceso" title="Del problema a una operación que se puede sostener."/><div className="principles motion-grid">{principles.map((p,i)=><div key={p}><span>{i+1}</span><p>{p}</p></div>)}</div><p className="section-note">Seguridad, permisos, trazabilidad y observabilidad acompañan el proceso de extremo a extremo.</p><p className="section-note">La complejidad crece solo cuando el problema lo exige: automatización tradicional, workflow con LLM, agente o sistema agéntico.</p><SectionCTA title="Revisemos dónde está el cuello de botella." description="Una conversación inicial permite definir alcance, riesgos y la forma más útil de avanzar."/></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Prueba de trabajo" title="Experiencia para conectar IA con la operación."/><div className="grid grid-3 motion-grid"><Card><p className="evidence-label">Proyecto cuantificado</p><h3>50 entrevistas → insights validados</h3><p>{focusGroupProject.summary}</p><div className="metric-row">{focusGroupProject.metrics?.map(metric=><strong key={metric}>{metric}</strong>)}</div></Card><Card><p className="evidence-label">Ingeniería regulada</p><h3>Backend Java y .NET, arquitectura y seguridad</h3><p>Experiencia en banca y software empresarial regulado: Java, .NET, Spring Boot, integración, resiliencia, seguridad y continuidad operativa.</p></Card><Card><p className="evidence-label">Datos y lenguaje</p><h3>Predictive AI y NLP</h3><p>Forecasting de demanda, analítica predictiva y automatización de lenguaje pre-LLM junto a arquitecturas generativas actuales.</p></Card></div><SectionCTA title="Aterricemos tu caso en una arquitectura operable." description="Revisamos los sistemas existentes, los datos y los controles antes de escalar."/></Container></section>
    <section className="section section-tint technology-section"><Container><div className="technology-decision"><div className="technology-intro"><p className="eyebrow">Decisión técnica</p><h2>¿Ya tienes una plataforma o aún debes decidirla?</h2><p>No necesitas una lista de herramientas: necesitas saber qué se integra bien con tu contexto y qué se puede operar con seguridad.</p></div><div className="decision-grid motion-grid"><article><span>01</span><h3>Ya tienes una plataforma</h3><p>Podemos trabajar con Claude, OpenAI/Codex, Vertex AI o AWS Bedrock sin forzar un cambio de proveedor.</p></article><article><span>02</span><h3>Necesitas definir el enfoque</h3><p>Evaluamos datos, APIs, permisos, costo, observabilidad y operación antes de elegir arquitectura.</p></article><article><span>03</span><h3>Quieres avanzar con control</h3><p>Diseñamos evaluación y revisión humana cuando el riesgo o la decisión de negocio lo requiere.</p></article></div><SectionCTA title="Conversemos antes de comprar o construir." description="Trae la plataforma, el proceso o la duda. Definimos el camino más útil para tu organización."/></div></Container></section>
    <section className="cta"><Container><h2>¿Tienes un proceso, producto o equipo que necesita avanzar con IA?</h2><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Hablar sobre el proyecto</Button></Container></section>
  </>
}
