import Button from '../components/Button'
import Card from '../components/Card'
import Container from '../components/Container'
import PageMeta from '../components/PageMeta'
import SectionHeading from '../components/SectionHeading'
import { capabilities, focusGroupProject, principles, primaryEcosystems, technicalEcosystems } from '../content'
import { whatsappUrl } from '../config'

export default function Home() {
  return <><PageMeta path="/" title="Neuracode | Consultoría de IA, Automatización y Agentes" description="Diseñamos e implementamos automatización con IA, agentes, analítica y software para empresas. Discovery, pilotos, integración, evaluación y formación." />
    <section className="hero"><Container><div className="hero-grid"><div>
      <p className="eyebrow">Neuracode · Enterprise + Academy</p><h1>Integramos IA en <span>procesos reales de negocio.</span></h1>
      <p className="hero-copy">Diseñamos e implementamos automatizaciones, agentes, sistemas de IA y software conectados a datos, APIs y operación. Desde discovery y arquitectura hasta piloto, integración, evaluación y producción.</p>
      <div className="actions"><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Hablar sobre un proyecto</Button><Button to="/casos" variant="secondary">Ver experiencia y casos</Button><Button to="/jack-aguilar" variant="ghost">Conocer a Jack Aguilar</Button></div>
    </div><div className="system-card" aria-label="Nuestro enfoque"><div className="system-line"><span>01</span><p><strong>Problema</strong> antes que herramienta</p></div><div className="system-line"><span>02</span><p><strong>Arquitectura</strong> suficiente y operable</p></div><div className="system-line"><span>03</span><p><strong>Evidencia</strong> antes que promesa</p></div><div className="system-line"><span>04</span><p><strong>Gobernanza</strong> proporcional al riesgo</p></div></div></div></Container></section>
    <section className="section proof-section"><Container><SectionHeading eyebrow="Experiencia aplicada" title="Proyectos y experiencia que conectan software, datos e IA."/><div className="grid grid-3"><Card><p className="evidence-label">{focusGroupProject.label}</p><h3>50 entrevistas → insights validados</h3><p>{focusGroupProject.summary}</p><div className="metric-row">{focusGroupProject.metrics?.map(metric=><strong key={metric}>{metric}</strong>)}</div></Card><Card><p className="evidence-label">Experiencia profesional</p><h3>Backend Java en banca regulada</h3><p>Backend Java, arquitectura e integraciones para sistemas financieros: Spring Boot, APIs REST/OpenAPI, HSM, transferencias inmediatas, biometría y continuidad operativa.</p></Card><Card><p className="evidence-label">IA aplicada</p><h3>IA más allá del LLM</h3><p>Experiencia en forecasting, modelos predictivos, NLP y automatización pre-LLM, además de sistemas actuales con LLMs y agentes.</p></Card></div><Button to="/casos" variant="secondary">Ver proyectos y experiencia</Button></Container></section>
    <section className="section section-tint"><Container><SectionHeading eyebrow="Capacidades Enterprise" title="Del proceso a un sistema que funciona." description="La tecnología se elige después de entender el contexto, los datos, las restricciones y el riesgo." /><div className="grid grid-4">{capabilities.map((item, i) => <Card key={item.title}><span className="card-index">0{i + 1}</span><h3>{item.title}</h3><p>{item.text}</p></Card>)}</div><Button to="/empresas" variant="secondary">Ver servicios para empresas</Button></Container></section>
    <section className="section ecosystem-section"><Container><SectionHeading eyebrow="Experiencia técnica" title="Plataformas, frameworks y patrones según el caso." description="La tecnología aparece después de entender el problema, la arquitectura existente y las condiciones de operación."/><div className="ecosystem-groups"><div><h3>Plataformas y herramientas</h3><div className="chip-row chip-row-primary">{primaryEcosystems.map(item=><span key={item}>{item}</span>)}</div></div><div><h3>Frameworks y patrones</h3><div className="chip-row">{technicalEcosystems.map(item=><span key={item}>{item}</span>)}</div></div></div><p className="ecosystem-qualifier">Seleccionamos modelo, proveedor y arquitectura según el caso. No forzamos un LLM o un agente cuando una solución más simple es suficiente.</p></Container></section>
    <section className="section section-dark"><Container><SectionHeading eyebrow="Cómo trabajamos" title="Descubrir. Diseñar. Probar. Operar." /><div className="principles">{principles.map((item, i) => <div key={item}><span>{i + 1}</span><p>{item}</p></div>)}</div></Container></section>
    <section className="section"><Container><div className="split"><div><p className="eyebrow">Ingeniería detrás de Neuracode</p><h2>Software, arquitectura, datos e IA aplicada.</h2><p>Jack Aguilar es Software Engineer &amp; AI Automation Consultant. Su experiencia combina backend, integraciones, arquitectura, datos, seguridad y sistemas regulados con automatización, LLMs y sistemas agénticos.</p><Button to="/jack-aguilar" variant="secondary">Conocer a Jack</Button></div><div><p className="eyebrow">Neuracode Academy</p><h2>Formación práctica para profesionales y equipos.</h2><p>Workshops y programas sobre IA aplicada, agentes, AI Engineering, AI Coding, SDLC y adopción segura, conectados con problemas reales de ingeniería y negocio.</p><Button to="/academy" variant="secondary">Explorar Academy</Button></div></div></Container></section>
    <section className="cta"><Container><p className="eyebrow">Primer paso</p><h2>Conversemos sobre el problema antes de elegir la solución.</h2><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Iniciar conversación</Button></Container></section>
  </>
}
