import Button from '../components/Button'
import Card from '../components/Card'
import Container from '../components/Container'
import PageMeta from '../components/PageMeta'
import SectionHeading from '../components/SectionHeading'
import { architectureCapabilities, buyerScenarios, focusGroupProject, jackTechnologyGroups, professionalExperience, resources } from '../content'
import { config, whatsappUrl } from '../config'

const profilePage = {'@context':'https://schema.org','@type':'ProfilePage','@id':'https://www.neuracode.dev/jack-aguilar#profile',url:'https://www.neuracode.dev/jack-aguilar',name:'Jack Aguilar | Consultor de IA, Automatización y Agentes',mainEntity:{'@type':'Person','@id':'https://www.neuracode.dev/jack-aguilar#person',name:'Jack Aguilar',jobTitle:'Software Engineer & AI Automation Consultant',url:'https://www.neuracode.dev/jack-aguilar',sameAs:config.socials.jack.map(s=>s.url),knowsAbout:['AI Automation','Software Architecture','Agentic Systems','Data & Predictive AI','Secure SDLC']}}
const deliveryStages = ['Proceso', 'Arquitectura', 'Integración', 'Piloto', 'Evaluación', 'Seguridad y controles', 'Operación']

export default function Jack() {
  return <><PageMeta path="/jack-aguilar" title="Jack Aguilar | Consultor de IA, Automatización y Agentes" description="Ingeniero de software y consultor en IA. Diseño automatizaciones, agentes y sistemas integrados a procesos, datos, APIs y software empresarial." />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(profilePage)}} />
    <section className="page-hero jack-hero"><Container><p className="eyebrow">Software · Architecture · AI</p><h1>Jack Aguilar</h1><p className="role">Software Engineer &amp; AI Automation Consultant</p><p>Ayudo a empresas a automatizar procesos e integrar IA en software, datos y operaciones reales.</p><p className="proof-line">Puedo entrar desde un proceso manual, un dashboard, una API, un producto existente o una iniciativa de IA y llevarlo desde discovery y arquitectura hasta piloto, integración, evaluación y operación.</p><div className="actions"><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Hablar sobre un proyecto</Button><Button to="/casos" variant="secondary">Ver proyectos y experiencia</Button></div></Container></section>
    <section className="section section-tint"><Container><SectionHeading eyebrow="Puedes llegar con..." title="Un problema, un proceso o incluso una herramienta ya elegida."/><div className="grid grid-3 scenario-grid">{buyerScenarios.map(item=><Card key={item}><p>“{item}”</p></Card>)}</div><ol className="delivery-flow" aria-label="Etapas de implementación">{deliveryStages.map((stage,index)=><li key={stage}><span>{String(index + 1).padStart(2,'0')}</span><strong>{stage}</strong></li>)}</ol></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Trabajo seleccionado" title="Problemas reales en los que he trabajado."/><div className="grid grid-3"><Card><p className="evidence-label">{focusGroupProject.label}</p><h3>{focusGroupProject.title}</h3><p>{focusGroupProject.summary}</p><div className="metric-row">{focusGroupProject.metrics?.map(metric=><strong key={metric}>{metric}</strong>)}</div><div className="chip-row">{focusGroupProject.tags.map(tag=><span key={tag}>{tag}</span>)}</div></Card><Card><p className="evidence-label">Experiencia profesional</p><h3>Ingeniería en banca regulada</h3><p>Backend y arquitectura de integraciones para banca regulada: APIs, seguridad, HSM, transferencias inmediatas, biometría y resiliencia.</p><div className="chip-row"><span>.NET</span><span>APIs</span><span>HSM</span><span>Security</span></div></Card><Card><p className="evidence-label">Engagement actual</p><h3>Documentación clínica asistida por voz</h3><p>Automatización de atención y documentación clínica asistida por voz, generando borradores estructurados y manteniendo revisión profesional.</p><div className="chip-row"><span>Voice AI</span><span>Workflow Automation</span><span>HITL</span></div></Card></div><Button to="/casos" variant="secondary">Ver todos los proyectos</Button></Container></section>
    <section className="section section-dark"><Container><SectionHeading eyebrow="Experiencia profesional" title="Software, arquitectura, datos e IA aplicada."/><div className="evidence-list">{professionalExperience.map(item=><article className="evidence-item" key={item.id}><p className="evidence-label">{item.label}</p><div><h3>{item.title}</h3>{item.organization&&<p className="organization">{item.organization}</p>}</div><div><p>{item.summary}</p><div className="chip-row">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></article>)}</div></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Arquitectura e integración" title="Trabajo por encima y por debajo del modelo." description="La IA empresarial depende de servicios, datos, permisos, integraciones y operación. Mi experiencia incluye diseño y evolución de arquitecturas de software, datos y cloud, además de sistemas distribuidos y legacy."/><div className="chip-row chip-row-primary">{architectureCapabilities.map(item=><span key={item}>{item}</span>)}</div></Container></section>
    <section className="section section-tint"><Container><SectionHeading eyebrow="Capacidad técnica" title="Tecnología agrupada por el papel que cumple."/><div className="technology-groups">{jackTechnologyGroups.map(group=><div key={group.label}><h3>{group.label}</h3><div className="chip-row">{group.items.map(item=><span key={item}>{item}</span>)}</div></div>)}</div></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Build · Research · Teach" title="Enseño lo que también implemento."/><div className="grid grid-3"><Card><h3>SDC Learning</h3><p>Instructor de Agentes de Inteligencia Artificial para profesionales que trabajan con arquitecturas LLM y sistemas agénticos.</p></Card><Card><h3>Neuracode Academy</h3><p>Workshops y formación práctica sobre IA, AI Engineering, AI Coding, SDLC y adopción aplicada.</p></Card><Card><h3>Enterprise Enablement</h3><p>Sesiones para equipos que necesitan conectar aprendizaje, procesos y decisiones de implementación.</p></Card></div></Container></section>
    <section className="section section-tint"><Container><SectionHeading eyebrow="Recursos" title="Ideas públicas y trabajo verificable."/><div className="grid grid-3">{resources.map(resource=><Card key={resource.id}><p className="evidence-label">{resource.type}</p><h3>{resource.title}</h3><p>{resource.summary}</p><a className="text-link" href={resource.url} target="_blank" rel="noreferrer">Abrir recurso ↗</a></Card>)}</div><div className="social-row">{config.socials.jack.map(s=><a key={s.label} href={s.url} target="_blank" rel="me noreferrer">{s.label} ↗</a>)}</div></Container></section>
    <section className="cta"><Container><h2>¿Tienes un proceso que estás evaluando mejorar con IA?</h2><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Conversemos</Button></Container></section>
  </>
}
