import Button from '../components/Button'
import Card from '../components/Card'
import Container from '../components/Container'
import PageMeta from '../components/PageMeta'
import SectionHeading from '../components/SectionHeading'
import { architectureCapabilityGroups, authorityExperience, buyerScenarios, deliveryStages, engineeringExperience, focusGroupProject, jackTechnologyGroups, resources } from '../content'
import { config, whatsappUrl } from '../config'

const profilePage = {'@context':'https://schema.org','@type':'ProfilePage','@id':'https://www.neuracode.dev/jack-aguilar#profile',url:'https://www.neuracode.dev/jack-aguilar',name:'Jack Aguilar | Consultor de IA, Automatización y Agentes',mainEntity:{'@type':'Person','@id':'https://www.neuracode.dev/jack-aguilar#person',name:'Jack Aguilar',jobTitle:'Software Engineer & AI Automation Consultant',url:'https://www.neuracode.dev/jack-aguilar',sameAs:config.socials.jack.map(s=>s.url),knowsAbout:['AI Automation','Software Architecture','Agentic Systems','Data & Predictive AI','Secure SDLC']}}

export default function Jack() {
  return <><PageMeta path="/jack-aguilar" title="Jack Aguilar | Consultor de IA, Automatización y Agentes" description="Ingeniero de software y consultor en IA. Diseño automatizaciones, agentes y sistemas integrados a procesos, datos, APIs y software empresarial." />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(profilePage)}} />
    <section className="page-hero jack-hero"><Container><p className="eyebrow">Software · Architecture · AI</p><h1>Jack Aguilar</h1><p className="role">Software Engineer &amp; AI Automation Consultant</p><p>Ayudo a empresas a automatizar procesos e integrar IA en software, datos y operaciones reales.</p><p className="proof-line">Puedo entrar desde un proceso manual, un dashboard, una API, un producto existente o una iniciativa de IA y llevarlo desde discovery y arquitectura hasta piloto, integración, evaluación y operación.</p><div className="actions"><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Hablar sobre un proyecto</Button><Button to="/casos" variant="secondary">Ver proyectos y experiencia</Button></div></Container></section>
    <section className="section section-tint scenarios-section"><Container><SectionHeading eyebrow="Puedes llegar con..." title="Un problema, un proceso o una herramienta ya elegida."/><div className="grid grid-3 scenario-grid">{buyerScenarios.map((item,index)=><Card key={item}><span className="scenario-index">{String(index + 1).padStart(2,'0')}</span><p>“{item}”</p></Card>)}</div></Container></section>
    <section className="section process-section"><Container><SectionHeading eyebrow="Cómo trabajo el problema" title="Del proceso a la operación."/><ol className="delivery-flow" aria-label="Etapas de implementación">{deliveryStages.map((stage,index)=><li key={stage.title}><span>{String(index + 1).padStart(2,'0')}</span><div><strong>{stage.title}</strong><p>{stage.description}</p></div></li>)}</ol><aside className="control-rail" aria-label="Controles transversales"><strong>Seguridad · permisos · trazabilidad · observabilidad</strong><p>Estos controles no aparecen al final: se definen y refinan desde la arquitectura hasta la operación.</p></aside></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Trabajo seleccionado" title="Problemas reales en los que he trabajado."/><div className="grid grid-3"><Card><p className="evidence-label">{focusGroupProject.label}</p><h3>{focusGroupProject.title}</h3><p>{focusGroupProject.summary}</p><div className="metric-row">{focusGroupProject.metrics?.map(metric=><strong key={metric}>{metric}</strong>)}</div><div className="chip-row">{focusGroupProject.tags.map(tag=><span key={tag}>{tag}</span>)}</div></Card><Card><p className="evidence-label">Experiencia profesional</p><h3>Ingeniería en banca regulada</h3><p>Backend y arquitectura de integraciones para banca regulada: APIs, seguridad, HSM, transferencias inmediatas, biometría y resiliencia.</p><div className="chip-row"><span>.NET</span><span>APIs</span><span>HSM</span><span>Security</span></div></Card><Card><p className="evidence-label">Engagement actual</p><h3>Documentación clínica asistida por voz</h3><p>Automatización de atención y documentación clínica asistida por voz, generando borradores estructurados y manteniendo revisión profesional.</p><div className="chip-row"><span>Voice AI</span><span>Workflow Automation</span><span>HITL</span></div></Card></div><Button to="/casos" variant="secondary">Ver todos los proyectos</Button></Container></section>
    <section className="section section-dark"><Container><SectionHeading eyebrow="Experiencia profesional" title="Software, arquitectura, datos e IA aplicada."/><div className="evidence-list">{engineeringExperience.map(item=><article className="evidence-item" key={item.id}><p className="evidence-label">{item.label}</p><div><h3>{item.title}</h3>{item.organization&&<p className="organization">{item.organization}</p>}</div><div><p>{item.summary}</p><div className="chip-row">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></article>)}</div></Container></section>
    <section className="section"><Container><div className="architecture-layout"><SectionHeading eyebrow="Arquitectura e integración" title="La IA empresarial funciona cuando se integra con los sistemas que ya existen." description="Una solución de IA no termina en el modelo. Para funcionar en producción debe conectarse con datos, APIs, permisos y procesos operativos. Mi trabajo abarca el diseño de arquitecturas e integraciones para incorporar IA en software existente, plataformas cloud y sistemas distribuidos, incluida la evolución de sistemas legacy."/><div className="capability-groups">{architectureCapabilityGroups.map(group=><div key={group.label}><h3>{group.label}</h3><div className="chip-row chip-row-primary">{group.items.map(item=><span key={item}>{item}</span>)}</div></div>)}</div></div></Container></section>
    <section className="section section-tint"><Container><SectionHeading eyebrow="Capacidad técnica" title="Capacidades y tecnologías por dominio."/><div className="technology-groups">{jackTechnologyGroups.map(group=><div key={group.label}><h3>{group.label}</h3><div className="chip-row">{group.items.map(item=><span key={item}>{item}</span>)}</div></div>)}</div></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Implement · Enable · Teach" title="La experiencia de implementación alimenta la formación."/><div className="authority-grid">{authorityExperience.map(item=><Card key={item.id}><p className="evidence-label">{item.label}</p><h3>{item.title}</h3><p>{item.summary}</p></Card>)}</div><div className="grid grid-3"><Card><h3>SDC Learning</h3><p>Formación para profesionales en arquitecturas LLM, sistemas agénticos y aplicación práctica de IA.</p></Card><Card><h3>Neuracode Academy</h3><p>Workshops y formación práctica sobre IA, AI Engineering, AI Coding, SDLC y adopción aplicada.</p></Card><Card><h3>Enterprise Enablement</h3><p>Sesiones para equipos que necesitan conectar aprendizaje, procesos y decisiones de implementación.</p></Card></div></Container></section>
    <section className="section section-tint"><Container><SectionHeading eyebrow="Recursos" title="Ideas, análisis y proyectos públicos."/><div className="grid grid-3">{resources.map(resource=><Card key={resource.id}><p className="evidence-label">{resource.type}</p><h3>{resource.title}</h3><p>{resource.summary}</p><a className="text-link" href={resource.url} target="_blank" rel="noreferrer">Abrir recurso ↗</a></Card>)}</div><div className="social-row">{config.socials.jack.map(s=><a key={s.label} href={s.url} target="_blank" rel="me noreferrer">{s.label} ↗</a>)}</div></Container></section>
    <section className="cta cta--jack"><Container><div className="cta-content"><p className="eyebrow">Siguiente paso</p><h2>¿Tienes un proceso que quieres mejorar con IA?</h2><p>Revisemos el proceso, los sistemas involucrados y qué tendría que cambiar antes de elegir una solución.</p><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Hablar sobre un proyecto</Button></div></Container></section>
  </>
}
