import Button from '../components/Button'
import Card from '../components/Card'
import Container from '../components/Container'
import PageMeta from '../components/PageMeta'
import SectionHeading from '../components/SectionHeading'
import { jackTechnologyGroups, professionalExperience, resources, selectedWork } from '../content'
import { config, whatsappUrl } from '../config'

const profilePage = {'@context':'https://schema.org','@type':'ProfilePage','@id':'https://www.neuracode.dev/jack-aguilar#profile',url:'https://www.neuracode.dev/jack-aguilar',name:'Jack Aguilar | Consultor de IA, Automatización y Agentes',mainEntity:{'@type':'Person','@id':'https://www.neuracode.dev/jack-aguilar#person',name:'Jack Aguilar',jobTitle:'Software Engineer & AI Automation Consultant',url:'https://www.neuracode.dev/jack-aguilar',sameAs:config.socials.jack.map(s=>s.url),knowsAbout:['AI Automation','Agentic Systems','Software Engineering','Data & Analytics','Secure SDLC']}}

export default function Jack(){return <>
  <PageMeta path="/jack-aguilar" title="Jack Aguilar | Consultor de IA, Automatización y Agentes" description="Ingeniero de software y consultor en IA. Diseño automatizaciones, agentes y sistemas con LLMs, datos y APIs para empresas. Claude, OpenAI/Codex y AWS Bedrock."/>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(profilePage)}}/>
  <section className="page-hero jack-hero"><Container><p className="eyebrow">Build · Research · Teach</p><h1>Jack Aguilar</h1><p className="role">Software Engineer &amp; AI Automation Consultant</p><p>Diseño e implemento automatizaciones, agentes y sistemas de IA integrados a procesos, datos y software empresarial.</p><p className="proof-line">Experiencia en banca regulada, software empresarial, sector público, utilities, telecomunicaciones, entretenimiento y formación.</p><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Hablar sobre un proyecto</Button></Container></section>
  <section className="section"><Container><SectionHeading eyebrow="Experiencia" title="Software, datos, seguridad e IA aplicada." description="Cada experiencia conserva su atribución y nivel de evidencia."/><div className="evidence-list">{professionalExperience.map(item=><article className="evidence-item" key={item.id}><p className="evidence-label">{item.label}</p><h3>{item.title}</h3>{item.organization&&<p className="organization">{item.organization}</p>}<p>{item.summary}</p><div className="chip-row">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>)}</div></Container></section>
  <section className="section section-tint"><Container><SectionHeading eyebrow="Trabajo seleccionado" title="Evidencia técnica pública."/><div className="grid grid-3">{selectedWork.map(item=><Card key={item.id}><p className="evidence-label">{item.label}</p><h3>{item.title}</h3><p>{item.summary}</p>{item.url&&<a className="text-link" href={item.url} target="_blank" rel="noreferrer">Ver proyecto ↗</a>}</Card>)}</div></Container></section>
  <section className="section ecosystem-section"><Container><SectionHeading eyebrow="Capacidad técnica" title="De la restricción a la decisión de implementación." description="Tecnologías agrupadas por el papel que cumplen, no como una pared de logos."/><div className="technology-groups">{jackTechnologyGroups.map(group=><div key={group.label}><h3>{group.label}</h3><div className="chip-row">{group.items.map(item=><span key={item}>{item}</span>)}</div></div>)}</div></Container></section>
  <section className="section section-dark"><Container><SectionHeading eyebrow="Build · Research · Teach" title="Construir, investigar y enseñar se refuerzan entre sí."/><div className="grid grid-3"><Card><h3>Build</h3><p>Sistemas integrados a procesos, datos, APIs y controles reales.</p></Card><Card><h3>Research</h3><p>Evaluación de arquitecturas, calidad, riesgo, costo y operación.</p></Card><Card><h3>Teach</h3><p>Instructor de Agentes de Inteligencia Artificial en SDC Learning y formación mediante Academy.</p></Card></div></Container></section>
  <section className="section"><Container><SectionHeading eyebrow="Recursos" title="Ideas públicas y trabajo verificable."/><div className="grid grid-3">{resources.map(resource=><Card key={resource.id}><p className="evidence-label">{resource.type}</p><h3>{resource.title}</h3><p>{resource.summary}</p><a className="text-link" href={resource.url} target="_blank" rel="noreferrer">Abrir recurso ↗</a></Card>)}</div><div className="social-row">{config.socials.jack.map(s=><a key={s.label} href={s.url} target="_blank" rel="me noreferrer">{s.label} ↗</a>)}</div></Container></section>
  <section className="cta"><Container><h2>¿Tienes un proceso que estás evaluando mejorar con IA?</h2><Button href={whatsappUrl('proyecto')} target="_blank" rel="noreferrer">Conversemos</Button></Container></section>
</>}
